app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^$',views.home, name='home'),
    url(r'^market/$', views.market, name='marketbase'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^mine/$', views.mine, name='mine'),

    url(r'^market/(?P<childcid>\d+)/(?P<sortid>\d+)/$', views.market, name='market'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    
    url(r'^checkemail/$',views.checkemail, name='checkemail'),
    url(r'^addcart/$', views.addcart, name='addcart'),
    url(r'^subcart/$', views.subcart, name='subcart'),
    url(r'^changecartselect/$', views.changecartselect, name='changecartselect'),
    url(r'^changecartall/$', views.changecartall, name='changecartall'),

    url(r'^generateorder/$', views.generateorder, name='generateorder'),
    url(r'^orderlist/$', views.orderlist, name='orderlist'),
    url(r'^orderdetail/(?P<identifier>[\d.]+)/$', views.orderdetail, name='orderdetail'),


]

axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.urls', namespace='app')),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
{#    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.4.0/css/bootstrap.min.css" rel="stylesheet">#}
    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'base/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
    <title>
        {% block title %}
            base
        {% endblock %}
    </title>
    {% block extcss %}
    {% endblock %}
</head>
<body>
{% block body %}
    {#头部#}
    {% block header %}
        <header>爱先蜂</header>
    {% endblock %}{#头部结束#}

    {#主体内容#}
    <div class="hidescroll">
        <div id="content">
            {% block content %}
                主体内容
            {% endblock %}
        </div>
    </div>{# 主体内容结束 #}

    {#底部导航#}
    {% block footer %}
        <footer>
            <a href="{% url 'app:home' %}" class="home">
                <div class="item">
                    <div class="img"><span></span></div>
                    <div class="name">首页</div>
                </div>
            </a>
            <a href="{% url 'app:marketbase' %}" class="market">
                <div class="item">
                    <div class="img"><span></span></div>
                    <div class="name">闪购超市</div>
                </div>
            </a>
            <a href="{% url 'app:cart' %}" class="cart">
                <div class="item">
                    <div class="img"><span></span></div>
                    <div class="name">购物车</div>
                </div>
            </a>
            <a href="{% url 'app:mine' %}" class="mine">
                <div class="item">
                    <div class="img"><span></span></div>
                    <div class="name">我的</div>
                </div>
            </a>
        </footer>
    {% endblock %}{#底部结束#}
{% endblock %}
</body>
</html>
{#<script src="{% static 'base/js/jquery1.11.1.min.js' %}"></script>#}
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<script src="{% static 'base/js/jquery.cookie.js' %}"></script>
<script src="https://cdn.bootcss.com/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="{% static 'base/js/base.js' %}"></script>
{% block extjs %}
{% endblock %}