app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^$',views.home, name='home'),
    url(r'^market/$', views.market, name='marketbase'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^mine/$', views.mine, name='mine'),

    url(r'^market/(?P<childcid>\d+)/(?P<sortid>\d+)/$', views.market, name='market'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    
    url(r'^checkemail/$',views.checkemail, name='checkemail'),
    url(r'^addcart/$', views.addcart, name='addcart'),
    url(r'^subcart/$', views.subcart, name='subcart'),
    url(r'^changecartselect/$', views.changecartselect, name='changecartselect'),
    url(r'^changecartall/$', views.changecartall, name='changecartall'),

    url(r'^generateorder/$', views.generateorder, name='generateorder'),
    url(r'^orderlist/$', views.orderlist, name='orderlist'),
    url(r'^orderdetail/(?P<identifier>[\d.]+)/$', views.orderdetail, name='orderdetail'),


]

axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.urls', namespace='app')),
]

templates/market/market.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    闪购超市
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'market/css/market.css' %}">
{% endblock %}

{% block content %}
<div class="market">
    <div class="type-slider">
        <ul>
            {% for foodtype in foodtypes %}
                <li class="type-item">
                    <span></span>
                    <a href="{% url 'app:marketbase' %}">
                    {% if forloop.counter == foodtype.typesort %}
                        {{ foodtype.typename }}
                    {% endif %}
                </a></li>
            {% endfor %}
        </ul>
    </div>
    <nav>
        <ul>
            <li id="category-bt">
                <span>全部类型</span>
                <i class="glyphicon glyphicon-chevron-up"></i>
            </li>
            <li id="sort-bt">
                <span>综合排序</span>
                <i class="glyphicon glyphicon-chevron-up"></i>
            </li>
        </ul>
    </nav>
    <div class="main-content">
        <div class="content-wrapper">
            <ul>
                {% for good in good_list %}
                    <li>
                    <a href="">
                        <img src="{{ good.productimg }}" alt="" class="goods-img">
                        <div class="goods-info">
                            <p class="name">{{ good.productlongname }}</p>
                            <p class="detailtag">
                                {% if good.isxf %}
                                    <span class="xf">精选</span>
                                {% endif %}
                            </p>
                            <p class="specifics">{{ good.specifics }}</p>
                            <p class="price">
                                <span class="now-price">{{ good.price }}</span>
                                <span class="market-price">{{ good.marketprice }}</span>
                            </p>
                        </div>
                    </a>
                    <div class="bt-wrapper">
                        <span class="glyphicon glyphicon-minus" data-goodsid="{{ good.id }}"></span>
                        <i class="num">
                            {% for cart in carts %}
                                {% if good.id == cart.goods.id %}
                                    {{ cart.number }}
                                {% endif %}
                            {% endfor %}

                        </i>
                        <span class="glyphicon glyphicon-plus" data-goodsid="{{ good.id }}"></span>
                    </div>
                </li>
                {% endfor %}

            </ul>
        </div>
        <div class="bounce-view category-view">
            <div class="bounce-wrapper">
                {% for childtype in childtype_list %}
                    <a href="{% url 'app:market' childtype.id 0 %}">{{ childtype.name }}</a>
                {% endfor %}
            </div>
        </div>
        <div class="bounce-view sort-view">
            <div class="bounce-wrapper">
                <a href="{% url 'app:market' childcid 0 %}">综合排序</a>
                <a href="{% url 'app:market' childcid 1 %}">销量排序</a>
                <a href="{% url 'app:market' childcid 2 %}">价格最低</a>
                <a href="{% url 'app:market' childcid 3 %}">价格最高</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extjs %}
    <script src="{% static 'market/js/market.js' %}"></script>
{% endblock %}