app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^$',views.home, name='home'),
    url(r'^market/$', views.market, name='marketbase'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^mine/$', views.mine, name='mine'),

    url(r'^market/(?P<childcid>\d+)/(?P<sortid>\d+)/$', views.market, name='market'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    
    url(r'^checkemail/$',views.checkemail, name='checkemail'),
    url(r'^addcart/$', views.addcart, name='addcart'),
    url(r'^subcart/$', views.subcart, name='subcart'),
    url(r'^changecartselect/$', views.changecartselect, name='changecartselect'),
    url(r'^changecartall/$', views.changecartall, name='changecartall'),

    url(r'^generateorder/$', views.generateorder, name='generateorder'),
    url(r'^orderlist/$', views.orderlist, name='orderlist'),
    url(r'^orderdetail/(?P<identifier>[\d.]+)/$', views.orderdetail, name='orderdetail'),


]

axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.urls', namespace='app')),
]

templates/mine/login.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
登录
{% endblock %}
{% block footer %}
{% endblock %}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/login.css' %}">
{% endblock %}
{% block content %}
<div class="login">
    <div class="back">
        <a href="{% url 'app:mine' %}">
            <span class=" glyphicon glyphicon-remove "></span>
        </a>
    </div>
    <form action="{% url 'app:login' %}" method="post">
        {% csrf_token %}
        <div class="input-group">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button">邮箱</button>
            </span>
            <input type="email" class="form-control" placeholder="邮箱" name="email">
        </div>
        <div class="input-group">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button">密码</button>
            </span>
            <input type="password" class="form-control" placeholder="输入密码" name="password">
        </div>
        <p style="color: red;">{{ error }}</p>
        <input type="submit" value="登录" id="subButton">
    </form>
</div>
{% endblock %}

{% block extjs %}
    <script src="{% static 'mine/js/login.js' %}"></script>
{% endblock %}

templates/mine/mine.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    我的
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{% endblock %}

{% block content %}
    <div class="mine">
        <div class="user-wrapper">
            <div class="user-img">
                <img src="/static/mine/img/{{ user.img | default:'axf.png' }}" alt="">
            </div>
            <div class="user-content">
                <p>
                    <span class="glyphicon glyphicon-user"></span>
                    <a id="login-a">{{ user.name | default:'未登录' }}</a>
                </p>
                <p>
                    <span class="glyphicon glyphicon-th-list"></span>
                    等级：{{ user.rank | default:'无' }}
                </p>
                <a href="{% url 'app:register' %}" class="register">注册</a>
            </div>
        </div>
        <div class="collect">
            <span class="glyphicon glyphicon-flash"></span>
            <i>商品收藏</i>
        </div>
        <div class="other">
            <section class="my">
                <span>我的订单</span>
                <a href="{% url 'app:orderlist' %}">查看全部订单 <i class="glyphicon glyphicon-chevron-right "></i> </a>
            </section>

            <section>
                <ul>
                    <li>
                        <a href="#">
                            <dl class="item">
                                <dt><span class="glyphicon glyphicon-gift"></span><span class="badge">{{ waitpay }}</span></dt>
                                <dd>待付款</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl class="item">
                                <dt><span class="glyphicon glyphicon-leaf"></span><span class="badge">{{ paydone }}</span></dt>
                                <dd>待收货</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-fire"></span></dt>
                                <dd>待评价</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-plane"></span></dt>
                                <dd>退款/售后</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </section>

            <section>
                <ul>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-random"></span></dt>
                                <dd>优惠劵</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-comment"></span></dt>
                                <dd>收货地址</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-magnet"></span></dt>
                                <dd>客户反馈</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-wrench"></span></dt>
                                <dd>关于我们</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </section>

            {% if user %}
                <section class="quit">
                    <a href="{% url 'app:logout' %}">
                        退出
                    </a>
                </section>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block extjs %}
    <script src="{% static 'mine/js/mine.js' %}"></script>
{% endblock %}

templates/mine/register.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
注册
{% endblock %}
{% block footer %}
{% endblock %}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/register.css' %}">
{% endblock %}
{% block content %}
<div class="register">
    <div class="back">
        <a href="{% url 'app:mine' %}">
            <span class=" glyphicon glyphicon-remove "></span>
        </a>
    </div>
    <form action="{% url 'app:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group has-feedback" id="email">
            <div class="input-group">
                <span class="input-group-addon">邮箱</span>
                <input type="text" class="form-control" placeholder="邮箱" name="email" id="email-t" data-toggle="popover" data-placement="bottom" data-content="格式不正确">
            </div>
            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
        </div>
        <div class="form-group has-feedback" id="password">
            <div class="input-group">
                <span class="input-group-addon">密码</span>
                <input type="password" class="form-control" placeholder="6位以上" name="password" id="password-t" data-toggle="popover" data-placement="bottom" data-content="格式不正确">
            </div>
            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
        </div>
        <div class="form-group has-feedback" id="verify-psd">
            <div class="input-group">
                <span class="input-group-addon">确认密码</span>
                <input type="password" class="form-control" placeholder="6位以上" id="verify-psd-t" data-toggle="popover" data-placement="bottom" data-content="密码不一致">
            </div>
            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
        </div>
        <div class="form-group has-feedback" id="nic-name">
            <div class="input-group">
                <span class="input-group-addon">昵称</span>
                <input type="text" class="form-control" placeholder="随便起个名字" name="name" id="nic-name-t" data-toggle="popover" data-placement="bottom" data-content="字数过短">
            </div>
            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
        </div>
{#        <input type="submit" value="注册" id="subButton">#}
    </form>
    <button id="subButton">注册</button>
</div>
{% endblock %}

{% block extjs %}
    <script src="{% static 'mine/js/register.js' %}"></script>
{% endblock %}